version: '3.4'

services:
  hexagonal-api:
    image: hexagonal-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 8080:8080
    healthcheck:
      test: wget --verbose --tries=1 --spider localhost:8080/actuator/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 5s

  tests:
    image: functional-tests
    build:
      context: .
      dockerfile: integrationtest/Dockerfile
    entrypoint: newman
    command: run HexagonalTestEcommerce.postman_collection.json --environment=hexagonal-environment.postman_environment.json  --reporters cli,json --reporter-json-export /data/results/outputfile.json
    volumes:
      - results:/data/results
    depends_on:
      hexagonal-api:
        condition: service_healthy

volumes:
  results:
